## 七月在线机器学习第九期第四阶段考试
#### 考试说明:
- 起止时间：请同学在2018年8月14日至8月17日期间完成，最晚提交时间（8月17日24时之前）结束，<b>逾期不接受补考,该考试分数计入平时成绩</b>
- 考试方式：请同学将该试卷进行复制后，改名为自己姓名后，如State4Exam-WangWei.ipynb，<b>移动</b>至/0.Teacher/Exam/Stage4/目录下后，进行答题。
- 注意事项：为确保同学们真正了解自身对本周课程的掌握程度，<font color=red><b>请勿翻阅，移动，更改</b></font>其它同学试卷。如发现按0分处理
- 请同学在下方同学姓名处填写自己的姓名，批改人和最终得分不用填写

- 同学姓名:
- 批改人：   
- 最终得分:

<center><h1>####答卷开始####</h1></center>
<hr>

## 问答题(共6题，前4题每题15分，最后两题每题20分。共计100分)

#### 1.谈谈马尔可夫模型中的无后效性思想？

#### 2.朴素贝叶斯为什么朴素？

#### 3.请简要谈谈LDA主题模型的思想？

#### 4.为什么说指定贝叶斯网络是Directed Acyclic Graph，为什么不能有向有环图？

#### 5.隐马链的后向解法是指？

#### 6.请结合有向无环图DAG,简要说说你对贝叶斯网络的了解？

***
<center><h1>####答卷结束####</h1></center>

In [16]:
import numpy as np
p=np.array([[.9,.1],[.5,.5]])#转移矩阵
step1000=p#稳态分布
for i in range(1000):
    step1000=step1000.dot(p)
print(step1000)#稳态分布
np.array([0,1]).dot(step1000)

[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]


array([0.83333333, 0.16666667])

In [12]:
temp.dot(p)

array([[0.83333333, 0.16666667],
       [0.83333333, 0.16666667]])